fixed pipeline v4

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -3,7 +3,6 @@ name: CI
 on:
   push:
     branches: [ "master" ]
-
   workflow_dispatch:
 
 jobs:
@@ -11,7 +10,51 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Check disk space
+        run: df . -h
+
+      - name: Free disk space
+        run: |
+          # Remove unused Docker images
+          sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
+          
+          # Delete unnecessary directories related to the Docker environment
+          sudo rm -rf /var/cache/apt/* /var/lib/apt/lists/* /tmp/* || true
+          echo "Some Docker-related directories deleted"
+          
+          # Clean up other unnecessary packages and files
+          sudo apt install aptitude -y >/dev/null 2>&1
+          sudo aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+            esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+            google-cloud-sdk imagemagick \
+            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+            mercurial apt-transport-https mono-complete libmysqlclient \
+            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+            sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable \
+            -y -f >/dev/null 2>&1
+          sudo apt-get autoremove -y >/dev/null 2>&1
+          sudo apt-get autoclean -y >/dev/null 2>&1
+          echo "Some packages purged"
+
+      - name: Check disk space again
+        run: |
+          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
+          df . -h
+          sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head
+
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Check working space directory
+        run: du ${GITHUB_WORKSPACE} -h -d 1
+
+      - name: Get more space
+        run: |
+          df . -h
+          sudo rm -rf ${GITHUB_WORKSPACE}/.git
+          df . -h
 
       - name: Log in to DockerHub
         uses: docker/login-action@v2
@@ -19,18 +62,12 @@ jobs:
           username: atomowkibe
           password: Admin123123
 
-      - name: Compress prestashop directory
-        run: |
-          tar -czf prestashop.tar.gz prestashop
-
       - name: Build Docker Image
         run: |
+          sudo rm -rf /var/www/html/var/cache/* /var/www/html/var/logs/* /var/www/html/var/sessions/*
+          
           docker build -f docker_compose/dockerfile -t atomowkibe/prestashop:latest .
 
       - name: Push Docker Image
         run: |
           docker push atomowkibe/prestashop:latest
-
-      - name: Clean up compressed files
-        run: |
-          rm -f prestashop.tar.gz
